#!/bin/bash

echo "🚀 GitHub Upload Helper for 7+ Academy CRM"
echo ""

echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. 📁 Create GitHub Repository:"
echo "   - Go to https://github.com"
echo "   - Click the '+' button → 'New repository'"
echo "   - Name it: 7plus-academy-crm"
echo "   - Make it PUBLIC (important!)"
echo "   - Click 'Create repository'"
echo ""
echo "2. 📤 Upload Files:"
echo "   - In your new repository, click 'uploading an existing file'"
echo "   - Drag and drop ALL files from this folder:"
echo "     $(pwd)"
echo "   - Click 'Commit changes'"
echo ""
echo "3. 🌐 Deploy to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Sign up with GitHub"
echo "   - Click 'New Project'"
echo "   - Import your repository"
echo "   - Click 'Deploy'"
echo ""
echo "4. 🔗 Get Your URL:"
echo "   - Your app will be at: https://7plus-academy-crm.vercel.app"
echo "   - Share this URL with your staff!"
echo ""
echo "📱 Demo Credentials:"
echo "   - Admin: admin / password123"
echo "   - Staff: staff_a / password123"
echo ""
echo "🎉 Your CRM will be live in minutes!"
echo ""
echo "📁 Files to upload:"
ls -la
echo ""
echo "✅ All files are ready for upload!" 